project_name: knaudit-proxy

before:
  hooks:
    - go mod download

builds:
  - id: darwin-amd
    main: ./cmd/knaudit-proxy
    binary: knaudit-proxy
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s
      - -w
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux-amd
    main: ./cmd/knaudit-proxy
    binary: knaudit-proxy
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -s
      - -w
    goos:
      - linux
    goarch:
      - amd64
  - id: linux-arm
    main: ./cmd/knaudit-proxy
    binary: knaudit-proxy
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s
      - -w
    goos:
      - linux
    goarch:
      - arm64

#dockers:
#  - image_templates:
#    - 'knaudit-proxy:{{ .Tag }}-amd64'
#    use: buildx
#    goos: linux
#    goarch: amd64
#    ids:
#    - linux-amd
#    dockerfile: Dockerfile-amd64
#    build_flag_templates:
#    - "--no-cache"
#    - "--pull"
#    - "--platform=linux/amd64"
#  - image_templates:
#    - 'knaudit-proxy:{{ .Tag }}-arm64'
#    use: buildx
#    goos: linux
#    goarch: arm64
#    ids:
#    - linux-arm
#    dockerfile: Dockerfile-arm64
#    build_flag_templates:
#    - "--no-cache"
#    - "--pull"
#    - "--platform=linux/arm64"

#docker_manifests:
#  - name_template: 'knaudit-proxy:{{ .Tag }}'
#    image_templates:
#      - 'knaudit-proxy:{{ .Tag }}-amd64'
#      - 'knaudit-proxy:{{ .Tag }}-arm64'

snapshot:
  name_template: "{{ .Tag }}"
