apiVersion: apps/v1
kind: Deployment
metadata:
  name: knaudit-proxy
  namespace: knada-system
  labels:
    app: knaudit-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knaudit-proxy
  template:
    metadata:
      labels:
        app: knaudit-proxy
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: knaudit-proxy
          image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knaudit-proxy
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          env:
            - name: "GIN_MODE"
              value: "release"
          envFrom:
            - secretRef:
                name: knaudit-oracle-url
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
