apiVersion: v1
kind: Service
metadata:
  name: knaudit-proxy
  namespace: knada-system
spec:
  type: ClusterIP
  ports:
  - name: knaudit-proxy
    port: 80
    targetPort: 8080
  selector:
    app: knaudit-proxy
