apiVersion: apps/v1
kind: Deployment
metadata:
  name: knaudit-proxy
  namespace: knada-system
  labels:
    app: knaudit-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knaudit-proxy
  template:
    metadata:
      labels:
        app: knaudit-proxy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      nodeSelector:
        knada-infrastructure: ""
      tolerations:
        - key: "knada-infrastructure"
          effect: "NoSchedule"
          operator: "Exists"
      containers:
        - name: knaudit-proxy
          image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knaudit-proxy
          command:
          - "/app/knaudit-proxy"
          args:
          - "-backend-type"
          - "oracle"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: knaudit-oracle-url
          resources:
            limits:
              memory: 32Mi
            requests:
              ephemeral-storage: 1Mi
              cpu: 10m
              memory: 16Mi
